apiVersion: v1
appVersion: "2021.02"
description: Launches a Slicer instance to explore files in Minio
name: slicer-chart
version: "0.1.0"
keywords:
- kaapanaapplication
- kaapanaint
- kaapanamultiinstallable
- kaapanaexperimental
