
apiVersion: v1
kind: Service
metadata:
  name: fastapi-postgres-service
  namespace: {{ .Values.global.base_namespace }}
  labels:
    app-name: fastapi-postgres
spec:
  selector:
    app-name: fastapi-postgres
  ports:
    - port: 5432
      targetPort: 5432