---
global:
    registry_url: ""
    pull_policy_pods: ""
    base_namespace: ""
    fast_data_dir: ""
    slow_data_dir: ""
    slow_mount_path: "/minio"
envVars:

volumeMounts:
# - name: workflowdata
#   mountPath: /root
volumes:
# - name: workflowdata
#   path: /home/kaapana/workflows/