http_proxy: ""
default_container_registry: "registry.gitlab.com/fedorov_lab/nadya-kaapana-registry"     # empty for local build or registry-url like 'dktk-jip-registry.dkfz.de/kaapana' or 'registry.hzdr.de/kaapana/kaapana'
log_level: "WARN"
build_containers: true
push_containers: true
push_dev_containers_only: false
build_charts: true
push_charts: true
create_package: true
